export interface worktime {
  sessionID: string,
  workTimeID: string,
  date: string,
  from: string,
  to: string, 
  breakShare?: string,
  duration: number,
  ticketID?: string,
  projectID?: string,
  taskID?: string, 
  activityID?: string,
  comment?: string,
  billable: boolean,
  reasonNotAccountableID?: string,
  iccID?: string,
  customFieldList: {
    abstractCustomField: {ID: string,
    context: string,
    name: string,
    mandatory: boolean,
    active: boolean,
    reportId?: string,
    validatorList?: string[],
    stringValue?: string}
  },
  state: string,
  personID: string, 
  exportDate?: string,
  personName: string, 
  ticketName?: string,
  projectName?: string, 
  taskName: string,
  activityName: string,
  reasonNotAccountableName?: string,
  iccName?: string,
  lastChangedDate: string,
}